# =====================================================================
# ���� ���� ������� � ������ ����������� ������� ��� ������
# ".gitlab-ci.yml" (� ����� �����������).
#
# �� ��� �� ���� ������ �� ������ - ��� ������ ������/����������
# ����� � ����� ����� ������� (plugin-pipeline.yml), ������� ��������
# � ��������� ��������� �����������. ����� �� ������ ���������� ����
# ������ �������� include.
#
# ����� ������ ����������: ���� ����������� �������� ������ CI
# (��������, ����� ���������� �������) - �������� ���� ���� �
# ��������� �����������, � �� �������������� ������� � ������
# �� �������� ������������ ��������.
# =====================================================================

include:
  # project - ���� � ���������� ����������� � ����� ��������
  - project: 'tor-dev/infra.revit-ci-templates'
    # ref - ����� ����� ����� ����������� ������������ (������ main)
    ref: main
    # file - ��� ���� ������� ������ ���������� �����������
    file: '/plugin-pipeline.yml'